apps/core/urls.py
from django.urls import path, include
from apps.core import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('history/', views.HistoryView.as_view(), name='history'),
    path('password-college/', views.PasswordCollegeView.as_view(), name='password_college'),
    # Documents
    path('documents/', views.DocumentListView.as_view(), name='documents_list'),
    path('documents/<int:pk>/', views.DocumentDetailView.as_view(), name='documents_detail'),
    # Collaborations
    path('cooperation/', views.CooperationView.as_view(), name='cooperation'),
    path('internationals/', views.InternationalCooperationListView.as_view(), name='internationals'),
    path('internationals/<slug:slug>/', views.InternationalCooperationDetailView.as_view(), name='international_detail'),
    # More
    path('reception-applicants/', views.ReceptionApplicantsView.as_view(), name='reception'),
    # Education Process
    path('education-processes/<int:pk>/', views.EduProcessDetailView.as_view(), name='edu_process_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from services.seo.urls import urlpatterns as seo_urlpatterns

urlpatterns = [
    path('', include(seo_urlpatterns)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('specialties/', include('apps.specialty.urls')),
    path('contacts/', include('apps.feedback.urls')),
    path('employee/', include('apps.employee.urls')),
    path('students/', include('apps.student.urls')),
    path('news/', include('apps.news.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += (
        static(settings.STATIC_URL, document_root=settings.STATIC_DIR) +
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    import debug_toolbar
    urlpatterns += i18n_patterns(path('__debug__/', include(debug_toolbar.urls)), )

apps/core/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.validators import FileExtensionValidator

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from ckeditor.fields import RichTextField

from common.utils import get_english_translit as get_slug
from common.upload_to_files import (
    document_files,
    cooperation_files,
    international_images,
    international_main_img,
    edu_process_files,
    international_pdf
)
from common.managers import ActiveManager
from common import constants as cons


class Cooperation(models.Model):
    """Сотрудничество"""
    title = models.CharField(_("Название"), max_length=255)
    file = models.FileField(_("Файл"), validators=[FileExtensionValidator(['pdf'])], upload_to=cooperation_files)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Сотрудничество')
        verbose_name_plural = _('Сотрудничество')


class InternationalCooperation(models.Model):
    """Международное сотрудничество"""
    title = models.CharField(_('Название'), max_length=230)
    slug = models.SlugField("URL", max_length=255, null=True, blank=True)
    description = RichTextField(_('Описание'), blank=True, null=True)
    image = ProcessedImageField(verbose_name=_('Фото'), upload_to=international_main_img, format='webp',
                                processors=[ResizeToFill(2268, 1296)], options={'quality': 90})

    file = models.FileField(_("Договор (PDF)"), validators=[FileExtensionValidator(['pdf'])],
                            upload_to=international_pdf, null=True, blank=True)

    objects = models.Manager()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        self.slug = get_slug(self.title)
        super(InternationalCooperation, self).save(*args, **kwargs)

    def get_absolute_url(self, **kwargs):
        return reverse('international_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('-created',)
        verbose_name = _('Международное сотрудничество')
        verbose_name_plural = _('Международные сотрудничество')


class InternationalCooperationImages(models.Model):
    """Фотографии Международное сотрудничество"""
    international = models.ForeignKey(InternationalCooperation, on_delete=models.CASCADE, related_name='images')
    image = ProcessedImageField(verbose_name=_('Фотография'), upload_to=international_images, format='webp', options={'quality': 80})

    def __str__(self):
        return str(self.international.title)

    class Meta:
        verbose_name = _('Фотография')
        verbose_name_plural = _('Фотографии')


class Document(models.Model):
    title = models.CharField(_("Название"), max_length=255)
    is_active = models.BooleanField(_("Активный"), default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Нормативный документ')
        verbose_name_plural = _('Нормативные документы')


class DocumentFile(models.Model):
    document = models.ForeignKey(Document, verbose_name=_("Документ"), on_delete=models.CASCADE, related_name='files')
    title = models.CharField(_("Название файла"), max_length=255)
    file = models.FileField(
        _("Файл"), validators=[FileExtensionValidator(['pdf', 'png', 'jpg', 'webp'])], upload_to=document_files
    )

    def __str__(self):
        return f'{self.document} - {self.title}'

    class Meta:
        verbose_name = _('Файл документа')
        verbose_name_plural = _('Файлы документа')


class EduProcess(models.Model):
    title = models.CharField(_("Название"), max_length=255)
    is_active = models.BooleanField(_("Активный"), default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Учебный процесс')
        verbose_name_plural = _('Учебные процессы')


class EduProcessFile(models.Model):
    process = models.ForeignKey(EduProcess, verbose_name=_("Документ"), on_delete=models.CASCADE, related_name='files')
    title = models.CharField(_("Название файла"), max_length=255)
    file = models.FileField(
        _("Файл"), validators=[FileExtensionValidator(['pdf', 'png', 'jpg', 'webp'])], upload_to=edu_process_files
    )

    def __str__(self):
        return f'{self.process} - {self.title}'

    class Meta:
        verbose_name = _('Файл учебного процесса')
        verbose_name_plural = _('Файлы учебных процессов')


class AbstractResume(models.Model):
    GENDER_CHOICES = (
        (cons.MEN, _('Мужской')),
        (cons.WOMEN, _('Женский'))
    )

    number = models.IntegerField(_('Порядковый номер'), null=True, blank=True, default=100)
    last_name = models.CharField(_('Фамилия'), max_length=50)
    first_name = models.CharField(_('Имя'), max_length=50)
    sur_name = models.CharField(_('Отчество'), max_length=50, null=True, blank=True)
    slug = models.SlugField(max_length=250, null=True, blank=True)
    gender = models.CharField(_('Пол'), max_length=10, choices=GENDER_CHOICES, default=cons.MEN)
    date_of_birth = models.DateField(_('День рождения'))
    description = RichTextField(verbose_name='Резюме')
    email = models.EmailField('Email', blank=True, null=True)
    instagram = models.URLField('instagram', blank=True, null=True)
    facebook = models.URLField('facebook', blank=True, null=True)

    is_active = models.BooleanField("Активный", default=True)

    objects = models.Manager()
    active = ActiveManager()

    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def get_full_name(self):
        """ Полное имя """
        if self.sur_name:
            return f'{self.last_name} {self.first_name} {self.sur_name}'
        return f'{self.last_name} {self.first_name}'

    def save(self, *args, **kwargs):
        self.slug = get_slug(self.get_full_name())
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.sur_name if self.sur_name else ""}'

apps/news/models.py
from django.db import models
from django.urls import reverse

from django.utils.translation import gettext_lazy as _
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from ckeditor.fields import RichTextField

from common.utils import get_english_translit as get_slug
from common.upload_to_files import news_main_img, news_news_img
from common.managers import ActiveManager


class AbstractNews(models.Model):
    title = models.CharField(_('Название'), max_length=200)
    slug = models.SlugField("URL", max_length=255, null=True, blank=True)
    description = RichTextField(_('Описание'), blank=True, null=True)
    youtube = models.URLField(_('Ссылка на видео'), null=True, blank=True)

    is_active = models.BooleanField(_('Статус'), default=True)

    objects = models.Manager()
    active = ActiveManager()

    created = models.DateTimeField(_("Создано"))
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        self.slug = get_slug(self.title)
        super().save(*args, **kwargs)


class News(AbstractNews):
    """Новости колледжа"""
    image = ProcessedImageField(verbose_name=_('Фото'), upload_to=news_main_img, format='webp',
                                processors=[ResizeToFill(2268, 1296)], options={'quality': 90})

    def get_absolute_url(self, **kwargs):
        return reverse('news_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('-created',)
        verbose_name = _('Новость')
        verbose_name_plural = _('Новости')


class NewsImages(models.Model):
    """Фотографии Новостях"""
    news = models.ForeignKey(News, on_delete=models.CASCADE, related_name='images')
    image = ProcessedImageField(verbose_name=_('Фотография'), upload_to=news_news_img,
                                format='webp', options={'quality': 80})

    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.news.title

    class Meta:
        ordering = ('created',)
        verbose_name = _('Фотография')
        verbose_name_plural = _('Фотографии')

apps/core/views.py
from django.db.models import Prefetch
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView, ListView, DetailView
from django.utils.translation import gettext_lazy as _

from apps.core.models import Cooperation, Document, DocumentFile, InternationalCooperation, \
    InternationalCooperationImages, EduProcess, EduProcessFile
from apps.news.models import News
from apps.specialty.models import Specialty
from apps.employee.models import Employee
from apps.student.models import StudentCouncil, StudentLive


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["specialties"] = Specialty.active.all()
        context["news"] = News.active.all()[:9]
        context["lives"] = StudentLive.active.all()[:9]
        context["employees"] = Employee.active.select_related('position')[:9]
        context["students"] = StudentCouncil.active.all()[:9]
        context["internationals"] = InternationalCooperation.objects.all()
        return context


class HistoryView(TemplateView):
    template_name = 'history.html'


class PasswordCollegeView(TemplateView):
    template_name = 'passport-college.html'


class DocumentListView(ListView):
    model = Document
    queryset = model.objects.all()
    context_object_name = 'documents'
    template_name = 'documents/list.html'


class DocumentDetailView(DetailView):
    model = Document
    queryset = model.objects.prefetch_related(
        Prefetch('files', DocumentFile.objects.all())
    )
    context_object_name = 'document'
    template_name = 'documents/detail.html'


class CooperationView(ListView):
    model = Cooperation
    queryset = model.objects.all()
    context_object_name = 'cooperation'
    template_name = 'collaborations/cooperation.html'


class InternationalCooperationListView(ListView):
    model = InternationalCooperation
    context_object_name = 'internationals'
    template_name = 'collaborations/internationals.html'


class InternationalCooperationDetailView(DetailView):
    model = InternationalCooperation
    queryset = model.objects.prefetch_related(
        Prefetch('images', InternationalCooperationImages.objects.only('image'))
    )
    slug_field = 'slug'
    context_object_name = 'international'
    template_name = 'collaborations/international-detail.html'


class ReceptionApplicantsView(ListView):
    model = Specialty
    queryset = model.active.all()
    context_object_name = 'specialties'
    template_name = 'reception.html'


class EduProcessDetailView(DetailView):
    model = EduProcess
    queryset = model.objects.prefetch_related(
        Prefetch('files', EduProcessFile.objects.all())
    )
    context_object_name = 'process'
    template_name = 'edu_process_detail.html'

apps/core/templates/edu_process_detail.html
{% extends 'base/base.html' %}
{% load static i18n %}

{% block title %}
    {{ process.title }}
{% endblock %}

{% block content %}
    <section class="section documents">
        <div class="container">
            <div class="row">
                <div class="title col-12 m-auto">
                    <span>{% trans 'Учебный процесс' %}</span>
                    <h3>{{ process.title }}</h3>
                </div>
                <ul class="cooperation-list col-12 m-auto">
                    {% for item in process.files.all %}
                        <li>
                            <a href="{{ item.file.url }}">
                                <i class="fa fa-file mr-2"></i>
                                {{ item.title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

apps/core/templates/index.html
{% extends 'base/base.html' %}
{% load static imagekit  i18n %}

{% block links %}
    <link rel="stylesheet" href="{% static 'dist/libs/glightbox/glightbox.min.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/libs/Swiper/swiper-bundle.min.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/libs/ebs-el-kitep/el-kitep.min.css' %}">
{% endblock %}

{% block content %}
    <section class="section header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-lg-6 col-md-6 header__title">
                    <h2>{% trans 'Бишкекский автомобильно-дорожный колледж имени Кусаина Кольбаева' %}</h2>
                    <p class="desc-body my-4">
                        {% trans 'Миссия колледжа' %}:
                        {% blocktrans %}Обеспечить высокое качество образования, вдохновляя студентов и преподавателей к постоянному развитию и достижению успеха.{% endblocktrans %}
                    </p>
                    <a href="{% url 'contacts' %}" class="btn btn-primary">{% trans 'Связаться с нами ' %}</a>
                </div>
                <div class="col-12 col-lg-6 col-md-6">
                    <div class="header__slider">
                        <div class="header__slider-item">
                            <img src="{% static 'dist/images/college/MY6H2223.webp' %}" alt="">
                        </div>
                        <div class="header__slider-item">
                            <img src="{% static 'dist/images/college/MY6H2254.webp' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section history">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6 col-md-6 pl-lg-5 mb-3">
                    <div class="title mb-3">
                        <span>{% trans 'История колледжа' %}</span>
                        <h3>{% trans 'История развития учебного заведения' %}</h3>
                    </div>
                    <p class="desc-body">
                        {% blocktrans %}Кыргызская Республика расположена в горной местности. Более 95% перевозок грузов и пассажиров осуществляется автомобильным транспортом и часть железнодорожным. Поэтому республика нуждалась в подготовке специалистов среднего звена, владеющих навыками обслуживания, эксплуатации автотранспорта и строительства автомобильных и железных дорог.{% endblocktrans %}
                    </p>
                 <p class="desc-body">
                        {% blocktrans %}В 1939 году при Фрунзенском индустриальном техникуме было создано автомобильное отделение из одной группы, которое готовило механиков по техническому обслуживанию и ремонту автомобилей. Первый выпуск из 14 человек состоялся в 1942 году.{% endblocktrans %}
                    </p>
                    <a href="{% url 'history' %}" class="btn btn-primary">{% trans 'Подробно' %}</a>
                </div>
                <div class="col-12 col-lg-6 col-md-6 mb-3">
                    <div class="video-banner">
                        <img src="{% static 'dist/images/college/MY6H2343.webp' %}" alt="">
                        <a class="glightbox video" href="https://youtu.be/VG6la-KzZkg?si=4m3Zl63XV-3EgVtJ">
                            <i class="fa fa-play"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section news">
        <div class="container">
            <div class="title">
                <span>{% trans 'Новости колледжа' %}</span>
                <h3><a href="{% url 'news_list' %}">{% trans 'Новости' %}</a></h3>
            </div>
            <div class="slider_tree slider">
                {% for item in news %}
                    <div class="card">
                        <a href="{{ item.get_absolute_url }}" class="card-link">
                            <div class="card-img">
                                {% generateimage 'main:thumbnail' source=item.image -- class="mypicture" %}
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">{{ item.title|truncatechars:63 }}</h4>
                            </div>
                            <div class="card-inner">
                                <span class="card-inner_btn_right">{{ item.created|date }}</span>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <section class="section specialties">
        <div class="container">
            <div class="title">
                <span>{% trans 'Наши специальности' %}</span>
                <h3><a href="#">{% trans 'Специальности' %}</a></h3>
            </div>
            <div class="slider_tree slider">
                {% for specialty in specialties %}
                    <div class="card">
                        <a href="{{ specialty.get_absolute_url }}" class="card-link">
                            <div class="card-img">
                                {% generateimage 'main:thumbnail' source=specialty.image -- class="mypicture" %}
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">{{ specialty.title|truncatechars:63 }}</h4>
                            </div>
                            <div class="card-inner">
                                <span class="card-inner_btn_left">{{ specialty.form_verbose }}</span>
                                <span class="card-inner_btn_right">{{ specialty.contract }} сом</span>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>


    <section class="el-kitep section header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-12">
                    <div class="feature-content pl-3 text-left">
                        <div class="title text-left ml-auto p-1 mb-3">
                            <span class="wow fadeInRight" data-wow-delay=".3s">
                                {% trans 'О библиотеке' %}
                            </span>
                            <h3 class="wow fadeInRight text-white" data-wow-delay=".5s">
                                {% trans 'Электронно-библиотечная система «Эл-Китеп»' %}
                            </h3>
                        </div>
                        <div class="feature-item wow fadeInUp" data-wow-delay=".5s">
                            <div class="banner-content">
                                <p class="text-white">
                                    {% blocktrans %}Это система доступа к копиям электронных учебников, научной и другой дополнительной литературы, с возможностью цитирования и иными сервисами работы с текстом. Также ЭБС включает в себя мультимедийные (аудиовизуальные, программные, интерактивные) продукты и материалы.{% endblocktrans %}
                                </p>
                                <div class="button mt-4">
                                    <a class="btn btn-primary white-bg mouse-dir border-white border-1" target="_blank" href="https://ebs.el-kitep.kg/">
                                        {% trans 'Перейти' %}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-12">
                    <div class="swiper el-kitep-book-slider wow fadeInRight" data-wow-delay=".5s">
                        <div class="swiper-wrapper"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section cooperation">
        <div class="container">
            <div class="title">
                <span>{% trans 'Студентам' %}</span>
                <h3><a href="{% url 'student_live_list' %}">{% trans 'Студенческая жизнь' %}</a></h3>
            </div>
            <div class="slider_tree slider">
                {% for live in lives %}
                    <div class="card international-card">
                        <a href="{{ live.get_absolute_url }}" class="card-link">
                            <div class="card-img">
                                {% generateimage 'main:thumbnail' source=live.image -- class="mypicture" %}
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">{{ live.title|truncatechars:63 }}</h4>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section class="section cooperation">
        <div class="container">
            <div class="title">
                <span>{% trans 'О колледже' %}</span>
                <h3><a href="{% url 'employees' %}">{% trans 'Структура' %}</a></h3>
            </div>
            <div class="slider_employee slider list_employee">
                {% for employee in employees %}
                    <a href="{{ employee.get_absolute_url }}" class="card">
                        <div class="image-content">
                            <span class="overlay"></span>
                            <div class="card-image">
                                <img src="{{ employee.image.url }}" class="card-img" alt="">
                            </div>
                        </div>
                        <div class="card-content">
                            <h2 class="name">{{ employee.get_full_name }}</h2>
                            <p class="description">{{ employee.position }}</p>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </section>
    <section class="section cooperation">
        <div class="container">
            <div class="title">
                <span>{% trans 'Студентам' %}</span>
                <h3><a href="{% url 'students' %}">{% trans 'Члены студенческого совета' %}</a></h3>
            </div>
            <div class="slider_employee slider list_employee">
                {% for student in students %}
                    <a href="{{ student.get_absolute_url }}" class="card">
                        <div class="image-content">
                            <span class="overlay"></span>
                            <div class="card-image">
                                <img src="{{ student.image.url }}" class="card-img" alt="">
                            </div>
                        </div>
                        <div class="card-content">
                            <h2 class="name">{{ student.get_full_name }}</h2>
                            <p class="description">{{ student.position }}</p>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </section>
    <section class="section cooperation">
        <div class="container">
            <div class="title">
                <span>{% trans 'Сотрудничество' %}</span>
                <h3><a href="{% url 'internationals' %}">{% trans 'Международное сотрудничество' %}</a></h3>
            </div>
            <div class="slider_tree slider">
                {% for international in internationals %}
                    <div class="card international-card">
                        <a href="{{ international.get_absolute_url }}" class="card-link">
                            <div class="card-img">
                                {% generateimage 'main:thumbnail' source=international.image -- class="mypicture" %}
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">{{ international.title|truncatechars:63 }}</h4>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script src="{% static 'dist/libs/glightbox/glightbox.min.js' %}"></script>
    <script type="text/javascript">
        GLightbox({
            'href': 'https://youtu.be/VG6la-KzZkg?si=4m3Zl63XV-3EgVtJ',
            'type': 'video',
            'source': 'youtube', //vimeo, youtube or local
            'width': 900,
            'autoplayVideos': true,
        });
    </script>
    <script src="{% static 'dist/libs/Swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'dist/libs/ebs-el-kitep/el-kitep.js' %}"></script>
{% endblock %}

apps/core/templates/passport-college.html
{% extends 'base/base.html' %}
{% load static i18n %}

{% block title %}
    {% trans 'Паспорт колледжа' %}
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'dist/libs/flipbook/flipbook.style.min.css' %}">
{% endblock %}

{% block content %}
    <section class="section password_college">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="title">
                        <span>{% trans 'О колледже' %}</span>
                        <h3>{% trans 'Паспорт колледжа' %}</h3>
                    </div>
                </div>
                <div class="col-12">
                    <div id="flip_book" style="height: 600px; position: relative;">
                        <input type="hidden" id="url_pdf" value="{% static 'dist/documents/college-passport-official.pdf' %}">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script src="{% static 'dist/libs/flipbook/js/flipbook.min.js' %}"></script>
    <script src="{% static 'dist/libs/flipbook/js/book.js' %}"></script>
{% endblock %}